server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:15432/quotes"
    username: postgres
    password: password
  jpa:
    open-in-view: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
